-- +migrate Up
CREATE TABLE IF NOT EXISTS students (
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    first_name VARCHAR(256) NOT NULL ,
    last_name VARCHAR(256) DEFAULT NULL,
    identity_number VARCHAR(256) UNIQUE DEFAULT NULL,
    email VARCHAR(256) UNIQUE NOT NULL ,
    address TEXT DEFAULT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)Engine=InnoDB;

-- +migrate Down
DROP TABLE IF EXISTS students;